[build-system]
requires = ["setuptools~=77.0"]
build-backend = "setuptools.build_meta"

[project]
name         = "home-assistant-frontend"
version      = "20250326.0"
license      = "Apache-2.0"
license-files = ["LICENSE*"]
description  = "The Usync Assistant frontend"
readme       = "README.md"
authors      = [
    {name = "The Usync Assistant Authors", email = "hello@home-assistant.io"}
]
requires-python = ">=3.13.0"

[project.urls]
"Homepage" = "https://github.com/home-assistant/frontend"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["hass_frontend*"]
